"""
ML Research narrative extractor.

Consumes ml_research_corpus.json generated by scripts/ingest_research_corpus.py.
"""

from __future__ import annotations

from typing import Dict, Iterable, List, Tuple

import numpy as np

MIN_LENGTH = 200


def extract_research_narratives(records: Iterable[Dict]) -> Tuple[List[str], np.ndarray, int]:
    narratives: List[str] = []
    outcomes: List[float] = []
    total = 0

    for record in records:
        total += 1
        narrative = record.get("narrative") or ""
        if len(narrative) < MIN_LENGTH:
            continue
        impact = record.get("impact_score") or len(narrative) / 150
        narratives.append(narrative)
        outcomes.append(float(impact))

    return narratives, np.asarray(outcomes, dtype=float), total

