"""
Bible Stories Data Collection
Collects discrete Bible stories with cultural persistence metrics
"""

import json
import time
from pathlib import Path
from typing import Dict, List
import requests
from datetime import datetime

class BibleStoryCollector:
    """Collects Bible stories and their cultural persistence metrics"""
    
    def __init__(self):
        self.stories = []
        self.output_dir = Path(__file__).parent.parent / "data" / "bible"
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def collect_stories(self) -> List[Dict]:
        """
        Collect major Bible stories with metadata and cultural persistence metrics
        
        Stories selected based on:
        - Narrative completeness (beginning/middle/end)
        - Discrete event structure
        - Named characters
        - Cultural recognition potential
        """
        
        stories = [
            # OLD TESTAMENT - High Recognition
            {
                "story_id": "creation",
                "name": "Creation of the World",
                "testament": "Old",
                "book": "Genesis",
                "chapters": "1-2",
                "verses": 56,
                "summary": "God creates the world in six days, resting on the seventh. He creates light, sky, land, plants, celestial bodies, animals, and finally humans in His image.",
                "characters": ["God", "Adam", "Eve"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 1.0,
                "estimated_cultural_persistence": 0.98
            },
            {
                "story_id": "cain_abel",
                "name": "Cain and Abel",
                "testament": "Old",
                "book": "Genesis",
                "chapters": "4",
                "verses": 16,
                "summary": "The first murder: Cain, a farmer, kills his brother Abel, a shepherd, out of jealousy when God favors Abel's offering over his own.",
                "characters": ["Cain", "Abel", "God"],
                "has_underdog": True,
                "has_villain": True,
                "has_miracle": False,
                "has_violence": True,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.7,
                "estimated_cultural_persistence": 0.82
            },
            {
                "story_id": "noahs_ark",
                "name": "Noah's Ark",
                "testament": "Old",
                "book": "Genesis",
                "chapters": "6-9",
                "verses": 89,
                "summary": "God floods the Earth to cleanse it of wickedness. Noah builds an ark and saves his family and pairs of every animal species.",
                "characters": ["Noah", "God", "Noah's family"],
                "has_underdog": True,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": True,
                "moral_clarity": "medium",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 1.0,
                "estimated_cultural_persistence": 0.96
            },
            {
                "story_id": "babel",
                "name": "Tower of Babel",
                "testament": "Old",
                "book": "Genesis",
                "chapters": "11",
                "verses": 9,
                "summary": "Humans attempt to build a tower to reach heaven. God confuses their languages, scattering them across the Earth.",
                "characters": ["God", "People of Babel"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "medium",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.6,
                "estimated_cultural_persistence": 0.75
            },
            {
                "story_id": "sodom_gomorrah",
                "name": "Sodom and Gomorrah",
                "testament": "Old",
                "book": "Genesis",
                "chapters": "19",
                "verses": 29,
                "summary": "God destroys the sinful cities of Sodom and Gomorrah with fire. Lot's family escapes, but his wife looks back and turns into a pillar of salt.",
                "characters": ["Lot", "Lot's wife", "God", "Angels"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": True,
                "moral_clarity": "medium",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.4,
                "estimated_cultural_persistence": 0.78
            },
            {
                "story_id": "abraham_isaac",
                "name": "Binding of Isaac",
                "testament": "Old",
                "book": "Genesis",
                "chapters": "22",
                "verses": 19,
                "summary": "God tests Abraham by commanding him to sacrifice his son Isaac. At the last moment, God provides a ram as a substitute.",
                "characters": ["Abraham", "Isaac", "God"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": True,
                "moral_clarity": "low",
                "visual_iconic": True,
                "metaphor_potential": "medium",
                "children_bible_inclusion": 0.5,
                "estimated_cultural_persistence": 0.71
            },
            {
                "story_id": "joseph_coat",
                "name": "Joseph and His Brothers",
                "testament": "Old",
                "book": "Genesis",
                "chapters": "37-45",
                "verses": 215,
                "summary": "Joseph, favored by his father with a colorful coat, is sold into slavery by his jealous brothers. He rises to power in Egypt and eventually saves his family from famine.",
                "characters": ["Joseph", "Jacob", "Joseph's brothers", "Pharaoh", "Potiphar"],
                "has_underdog": True,
                "has_villain": True,
                "has_miracle": True,
                "has_violence": True,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.9,
                "estimated_cultural_persistence": 0.88
            },
            {
                "story_id": "moses_burning_bush",
                "name": "Moses and the Burning Bush",
                "testament": "Old",
                "book": "Exodus",
                "chapters": "3",
                "verses": 22,
                "summary": "God appears to Moses in a burning bush, calling him to lead the Israelites out of Egyptian slavery.",
                "characters": ["Moses", "God"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.8,
                "estimated_cultural_persistence": 0.85
            },
            {
                "story_id": "ten_plagues",
                "name": "The Ten Plagues of Egypt",
                "testament": "Old",
                "book": "Exodus",
                "chapters": "7-12",
                "verses": 142,
                "summary": "God sends ten devastating plagues upon Egypt to convince Pharaoh to free the Israelites. The final plague kills all firstborn sons.",
                "characters": ["Moses", "Aaron", "Pharaoh", "God"],
                "has_underdog": True,
                "has_villain": True,
                "has_miracle": True,
                "has_violence": True,
                "moral_clarity": "medium",
                "visual_iconic": True,
                "metaphor_potential": "medium",
                "children_bible_inclusion": 0.8,
                "estimated_cultural_persistence": 0.83
            },
            {
                "story_id": "red_sea",
                "name": "Parting of the Red Sea",
                "testament": "Old",
                "book": "Exodus",
                "chapters": "14",
                "verses": 31,
                "summary": "Pursued by Pharaoh's army, Moses parts the Red Sea, allowing the Israelites to cross safely. The waters return, drowning the Egyptian army.",
                "characters": ["Moses", "Pharaoh", "Israelites", "God"],
                "has_underdog": True,
                "has_villain": True,
                "has_miracle": True,
                "has_violence": True,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.95,
                "estimated_cultural_persistence": 0.94
            },
            {
                "story_id": "ten_commandments",
                "name": "The Ten Commandments",
                "testament": "Old",
                "book": "Exodus",
                "chapters": "20",
                "verses": 17,
                "summary": "God gives Moses the Ten Commandments on Mount Sinai, establishing the moral law for the Israelites.",
                "characters": ["Moses", "God"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.9,
                "estimated_cultural_persistence": 0.92
            },
            {
                "story_id": "golden_calf",
                "name": "The Golden Calf",
                "testament": "Old",
                "book": "Exodus",
                "chapters": "32",
                "verses": 35,
                "summary": "While Moses receives the commandments, the Israelites build and worship a golden calf. Moses destroys the idol in rage.",
                "characters": ["Moses", "Aaron", "Israelites", "God"],
                "has_underdog": False,
                "has_villain": True,
                "has_miracle": False,
                "has_violence": True,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.6,
                "estimated_cultural_persistence": 0.68
            },
            {
                "story_id": "walls_jericho",
                "name": "Battle of Jericho",
                "testament": "Old",
                "book": "Joshua",
                "chapters": "6",
                "verses": 27,
                "summary": "Joshua leads the Israelites around the walls of Jericho for seven days. On the seventh day, they blow trumpets and shout, causing the walls to collapse.",
                "characters": ["Joshua", "Israelites", "God"],
                "has_underdog": True,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": True,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.8,
                "estimated_cultural_persistence": 0.86
            },
            {
                "story_id": "samson_delilah",
                "name": "Samson and Delilah",
                "testament": "Old",
                "book": "Judges",
                "chapters": "16",
                "verses": 31,
                "summary": "Samson, a man of supernatural strength, is betrayed by Delilah who cuts his hair (the source of his power). Captured and blinded, he destroys a Philistine temple in his final act.",
                "characters": ["Samson", "Delilah", "Philistines"],
                "has_underdog": True,
                "has_villain": True,
                "has_miracle": True,
                "has_violence": True,
                "moral_clarity": "medium",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.7,
                "estimated_cultural_persistence": 0.89
            },
            {
                "story_id": "david_goliath",
                "name": "David and Goliath",
                "testament": "Old",
                "book": "1 Samuel",
                "chapters": "17",
                "verses": 58,
                "summary": "Young shepherd David defeats the giant warrior Goliath with a single stone from his sling, saving Israel from Philistine conquest.",
                "characters": ["David", "Goliath", "Saul", "Philistines"],
                "has_underdog": True,
                "has_villain": True,
                "has_miracle": False,
                "has_violence": True,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "extreme",
                "children_bible_inclusion": 1.0,
                "estimated_cultural_persistence": 0.99
            },
            {
                "story_id": "david_bathsheba",
                "name": "David and Bathsheba",
                "testament": "Old",
                "book": "2 Samuel",
                "chapters": "11-12",
                "verses": 52,
                "summary": "King David commits adultery with Bathsheba and arranges her husband Uriah's death in battle. God sends Nathan the prophet to confront David.",
                "characters": ["David", "Bathsheba", "Uriah", "Nathan", "God"],
                "has_underdog": False,
                "has_villain": True,
                "has_miracle": False,
                "has_violence": True,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "medium",
                "children_bible_inclusion": 0.2,
                "estimated_cultural_persistence": 0.64
            },
            {
                "story_id": "solomon_judgment",
                "name": "Solomon's Judgment",
                "testament": "Old",
                "book": "1 Kings",
                "chapters": "3",
                "verses": 28,
                "summary": "Two women claim to be the mother of the same baby. Solomon proposes cutting the baby in half, revealing the true mother by her willingness to give up the child.",
                "characters": ["Solomon", "Two mothers"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": False,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.75,
                "estimated_cultural_persistence": 0.87
            },
            {
                "story_id": "elijah_prophets_baal",
                "name": "Elijah and the Prophets of Baal",
                "testament": "Old",
                "book": "1 Kings",
                "chapters": "18",
                "verses": 46,
                "summary": "Elijah challenges 450 prophets of Baal to a contest. Their god fails to answer, but God sends fire from heaven to consume Elijah's sacrifice.",
                "characters": ["Elijah", "Prophets of Baal", "Ahab", "God"],
                "has_underdog": True,
                "has_villain": True,
                "has_miracle": True,
                "has_violence": True,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "medium",
                "children_bible_inclusion": 0.5,
                "estimated_cultural_persistence": 0.58
            },
            {
                "story_id": "jonah_whale",
                "name": "Jonah and the Whale",
                "testament": "Old",
                "book": "Jonah",
                "chapters": "1-4",
                "verses": 48,
                "summary": "Jonah flees from God's command to preach to Nineveh. Swallowed by a great fish, he prays for three days before being released to complete his mission.",
                "characters": ["Jonah", "God", "People of Nineveh"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "medium",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.95,
                "estimated_cultural_persistence": 0.91
            },
            {
                "story_id": "daniel_lions",
                "name": "Daniel in the Lions' Den",
                "testament": "Old",
                "book": "Daniel",
                "chapters": "6",
                "verses": 28,
                "summary": "Daniel continues to pray to God despite a royal decree forbidding it. Thrown into a den of lions, he is miraculously protected through the night.",
                "characters": ["Daniel", "Darius", "God"],
                "has_underdog": True,
                "has_villain": True,
                "has_miracle": True,
                "has_violence": True,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.9,
                "estimated_cultural_persistence": 0.88
            },
            
            # OLD TESTAMENT - Lower Recognition (The Blind Spot Stories)
            {
                "story_id": "jephthah_daughter",
                "name": "Jephthah's Daughter",
                "testament": "Old",
                "book": "Judges",
                "chapters": "11",
                "verses": 40,
                "summary": "Jephthah vows to sacrifice the first thing that greets him if he wins battle. His daughter comes out to meet him, and he fulfills his vow.",
                "characters": ["Jephthah", "Jephthah's daughter"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": False,
                "has_violence": True,
                "moral_clarity": "low",
                "visual_iconic": False,
                "metaphor_potential": "low",
                "children_bible_inclusion": 0.0,
                "estimated_cultural_persistence": 0.08
            },
            {
                "story_id": "ehud_eglon",
                "name": "Ehud Assassinates Eglon",
                "testament": "Old",
                "book": "Judges",
                "chapters": "3",
                "verses": 30,
                "summary": "Ehud, a left-handed judge, assassinates the obese King Eglon by stabbing him in the belly. The fat closes over the blade.",
                "characters": ["Ehud", "Eglon"],
                "has_underdog": True,
                "has_villain": True,
                "has_miracle": False,
                "has_violence": True,
                "moral_clarity": "medium",
                "visual_iconic": False,
                "metaphor_potential": "low",
                "children_bible_inclusion": 0.0,
                "estimated_cultural_persistence": 0.05
            },
            {
                "story_id": "jael_sisera",
                "name": "Jael Kills Sisera",
                "testament": "Old",
                "book": "Judges",
                "chapters": "4",
                "verses": 24,
                "summary": "Jael, a woman, kills the enemy commander Sisera by driving a tent peg through his temple while he sleeps.",
                "characters": ["Jael", "Sisera", "Deborah", "Barak"],
                "has_underdog": True,
                "has_villain": True,
                "has_miracle": False,
                "has_violence": True,
                "moral_clarity": "medium",
                "visual_iconic": True,
                "metaphor_potential": "low",
                "children_bible_inclusion": 0.1,
                "estimated_cultural_persistence": 0.15
            },
            {
                "story_id": "levites_concubine",
                "name": "The Levite's Concubine",
                "testament": "Old",
                "book": "Judges",
                "chapters": "19",
                "verses": 30,
                "summary": "A Levite's concubine is raped to death by men of Gibeah. He cuts her body into twelve pieces and sends them throughout Israel, sparking civil war.",
                "characters": ["Levite", "Concubine", "Men of Gibeah"],
                "has_underdog": False,
                "has_villain": True,
                "has_miracle": False,
                "has_violence": True,
                "moral_clarity": "low",
                "visual_iconic": False,
                "metaphor_potential": "low",
                "children_bible_inclusion": 0.0,
                "estimated_cultural_persistence": 0.02
            },
            {
                "story_id": "elisha_bears",
                "name": "Elisha and the She-Bears",
                "testament": "Old",
                "book": "2 Kings",
                "chapters": "2",
                "verses": 25,
                "summary": "Young boys mock the prophet Elisha for being bald. He curses them, and two bears come out of the woods and maul forty-two children.",
                "characters": ["Elisha", "Young boys", "Bears"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": True,
                "moral_clarity": "low",
                "visual_iconic": True,
                "metaphor_potential": "low",
                "children_bible_inclusion": 0.0,
                "estimated_cultural_persistence": 0.12
            },
            {
                "story_id": "uzzah_ark",
                "name": "Uzzah Touches the Ark",
                "testament": "Old",
                "book": "2 Samuel",
                "chapters": "6",
                "verses": 23,
                "summary": "Uzzah reaches out to steady the Ark of the Covenant when oxen stumble. God strikes him dead for touching the sacred object.",
                "characters": ["Uzzah", "David", "God"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": True,
                "moral_clarity": "low",
                "visual_iconic": False,
                "metaphor_potential": "low",
                "children_bible_inclusion": 0.0,
                "estimated_cultural_persistence": 0.06
            },
            {
                "story_id": "zimri_cozbi",
                "name": "Phinehas and the Spear",
                "testament": "Old",
                "book": "Numbers",
                "chapters": "25",
                "verses": 18,
                "summary": "An Israelite man brings a Midianite woman into camp. Phinehas follows them into a tent and drives a spear through both of them, stopping a plague.",
                "characters": ["Phinehas", "Zimri", "Cozbi"],
                "has_underdog": False,
                "has_villain": True,
                "has_miracle": False,
                "has_violence": True,
                "moral_clarity": "low",
                "visual_iconic": False,
                "metaphor_potential": "low",
                "children_bible_inclusion": 0.0,
                "estimated_cultural_persistence": 0.03
            },
            
            # NEW TESTAMENT - High Recognition
            {
                "story_id": "nativity",
                "name": "The Nativity",
                "testament": "New",
                "book": "Luke",
                "chapters": "2",
                "verses": 20,
                "summary": "Jesus is born in a manger in Bethlehem. Angels announce his birth to shepherds, and wise men follow a star to bring gifts.",
                "characters": ["Mary", "Joseph", "Jesus", "Shepherds", "Wise Men", "Angels"],
                "has_underdog": True,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 1.0,
                "estimated_cultural_persistence": 0.99
            },
            {
                "story_id": "baptism_jesus",
                "name": "Baptism of Jesus",
                "testament": "New",
                "book": "Matthew",
                "chapters": "3",
                "verses": 17,
                "summary": "John the Baptist baptizes Jesus in the Jordan River. The heavens open, and God's voice declares Jesus as His beloved Son.",
                "characters": ["Jesus", "John the Baptist", "God"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "medium",
                "children_bible_inclusion": 0.8,
                "estimated_cultural_persistence": 0.76
            },
            {
                "story_id": "temptation_jesus",
                "name": "Temptation of Jesus",
                "testament": "New",
                "book": "Matthew",
                "chapters": "4",
                "verses": 11,
                "summary": "After fasting for forty days in the wilderness, Jesus is tempted three times by Satan. He resists each temptation with scripture.",
                "characters": ["Jesus", "Satan"],
                "has_underdog": False,
                "has_villain": True,
                "has_miracle": False,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.7,
                "estimated_cultural_persistence": 0.72
            },
            {
                "story_id": "sermon_mount",
                "name": "Sermon on the Mount",
                "testament": "New",
                "book": "Matthew",
                "chapters": "5-7",
                "verses": 111,
                "summary": "Jesus delivers his most famous sermon, including the Beatitudes, the Lord's Prayer, and teachings on loving enemies and not judging others.",
                "characters": ["Jesus", "Disciples", "Crowd"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": False,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "extreme",
                "children_bible_inclusion": 0.6,
                "estimated_cultural_persistence": 0.81
            },
            {
                "story_id": "water_wine",
                "name": "Water into Wine",
                "testament": "New",
                "book": "John",
                "chapters": "2",
                "verses": 11,
                "summary": "At a wedding in Cana, Jesus performs his first miracle by turning water into wine at his mother's request.",
                "characters": ["Jesus", "Mary", "Disciples"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "medium",
                "visual_iconic": True,
                "metaphor_potential": "medium",
                "children_bible_inclusion": 0.6,
                "estimated_cultural_persistence": 0.73
            },
            {
                "story_id": "good_samaritan",
                "name": "The Good Samaritan",
                "testament": "New",
                "book": "Luke",
                "chapters": "10",
                "verses": 17,
                "summary": "Jesus tells a parable about a Samaritan who helps a beaten traveler after a priest and Levite pass by. The parable defines 'neighbor' and compassion.",
                "characters": ["Good Samaritan", "Injured man", "Priest", "Levite"],
                "has_underdog": True,
                "has_villain": False,
                "has_miracle": False,
                "has_violence": True,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "extreme",
                "children_bible_inclusion": 0.9,
                "estimated_cultural_persistence": 0.95
            },
            {
                "story_id": "prodigal_son",
                "name": "The Prodigal Son",
                "testament": "New",
                "book": "Luke",
                "chapters": "15",
                "verses": 32,
                "summary": "A son demands his inheritance early, squanders it, and returns home destitute. His father celebrates his return, angering the dutiful older brother.",
                "characters": ["Prodigal son", "Father", "Older brother"],
                "has_underdog": True,
                "has_villain": False,
                "has_miracle": False,
                "has_violence": False,
                "moral_clarity": "medium",
                "visual_iconic": True,
                "metaphor_potential": "extreme",
                "children_bible_inclusion": 0.85,
                "estimated_cultural_persistence": 0.93
            },
            {
                "story_id": "lazarus_raised",
                "name": "Raising of Lazarus",
                "testament": "New",
                "book": "John",
                "chapters": "11",
                "verses": 57,
                "summary": "Jesus raises his friend Lazarus from the dead after four days in the tomb, demonstrating his power over death.",
                "characters": ["Jesus", "Lazarus", "Mary", "Martha"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.7,
                "estimated_cultural_persistence": 0.79
            },
            {
                "story_id": "feeding_5000",
                "name": "Feeding the 5000",
                "testament": "New",
                "book": "Matthew",
                "chapters": "14",
                "verses": 21,
                "summary": "Jesus multiplies five loaves of bread and two fish to feed a crowd of 5,000 people, with twelve baskets of leftovers.",
                "characters": ["Jesus", "Disciples", "Crowd"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.85,
                "estimated_cultural_persistence": 0.84
            },
            {
                "story_id": "walking_water",
                "name": "Walking on Water",
                "testament": "New",
                "book": "Matthew",
                "chapters": "14",
                "verses": 33,
                "summary": "Jesus walks on water during a storm. Peter tries to walk to him but begins to sink when he loses faith. Jesus saves him.",
                "characters": ["Jesus", "Peter", "Disciples"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.8,
                "estimated_cultural_persistence": 0.87
            },
            {
                "story_id": "last_supper",
                "name": "The Last Supper",
                "testament": "New",
                "book": "Matthew",
                "chapters": "26",
                "verses": 30,
                "summary": "Jesus shares a final meal with his disciples, instituting communion. He predicts his betrayal and denial.",
                "characters": ["Jesus", "Disciples", "Judas", "Peter"],
                "has_underdog": False,
                "has_villain": True,
                "has_miracle": False,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "high",
                "children_bible_inclusion": 0.8,
                "estimated_cultural_persistence": 0.90
            },
            {
                "story_id": "crucifixion",
                "name": "The Crucifixion",
                "testament": "New",
                "book": "Matthew",
                "chapters": "27",
                "verses": 66,
                "summary": "Jesus is betrayed, tried, and crucified. He dies on the cross for humanity's sins. Darkness covers the land, and the temple curtain tears.",
                "characters": ["Jesus", "Judas", "Pilate", "Roman soldiers", "Mary", "John"],
                "has_underdog": True,
                "has_villain": True,
                "has_miracle": True,
                "has_violence": True,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "extreme",
                "children_bible_inclusion": 0.9,
                "estimated_cultural_persistence": 0.98
            },
            {
                "story_id": "resurrection",
                "name": "The Resurrection",
                "testament": "New",
                "book": "Matthew",
                "chapters": "28",
                "verses": 20,
                "summary": "Three days after his crucifixion, Jesus rises from the dead. Angels announce his resurrection, and he appears to his followers.",
                "characters": ["Jesus", "Mary Magdalene", "Angels", "Disciples"],
                "has_underdog": True,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "extreme",
                "children_bible_inclusion": 1.0,
                "estimated_cultural_persistence": 0.98
            },
            {
                "story_id": "road_emmaus",
                "name": "Road to Emmaus",
                "testament": "New",
                "book": "Luke",
                "chapters": "24",
                "verses": 35,
                "summary": "Two disciples walk to Emmaus, discussing Jesus's death. A stranger joins them and explains scripture. They recognize him as Jesus when he breaks bread.",
                "characters": ["Jesus", "Cleopas", "Another disciple"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "medium",
                "visual_iconic": True,
                "metaphor_potential": "medium",
                "children_bible_inclusion": 0.4,
                "estimated_cultural_persistence": 0.48
            },
            {
                "story_id": "doubting_thomas",
                "name": "Doubting Thomas",
                "testament": "New",
                "book": "John",
                "chapters": "20",
                "verses": 31,
                "summary": "Thomas doubts Jesus's resurrection until Jesus appears and invites him to touch his wounds. Thomas believes, and Jesus blesses those who believe without seeing.",
                "characters": ["Jesus", "Thomas", "Disciples"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "extreme",
                "children_bible_inclusion": 0.7,
                "estimated_cultural_persistence": 0.85
            },
            {
                "story_id": "pentecost",
                "name": "Pentecost",
                "testament": "New",
                "book": "Acts",
                "chapters": "2",
                "verses": 47,
                "summary": "The Holy Spirit descends on the apostles as tongues of fire. They speak in many languages, and Peter preaches, converting thousands.",
                "characters": ["Peter", "Apostles", "Crowd", "Holy Spirit"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "medium",
                "children_bible_inclusion": 0.6,
                "estimated_cultural_persistence": 0.65
            },
            {
                "story_id": "saul_conversion",
                "name": "Conversion of Saul",
                "testament": "New",
                "book": "Acts",
                "chapters": "9",
                "verses": 31,
                "summary": "Saul, a persecutor of Christians, is struck blind by a vision of Jesus on the road to Damascus. He converts and becomes Paul the Apostle.",
                "characters": ["Saul/Paul", "Jesus", "Ananias"],
                "has_underdog": True,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": True,
                "metaphor_potential": "extreme",
                "children_bible_inclusion": 0.7,
                "estimated_cultural_persistence": 0.82
            },
            
            # NEW TESTAMENT - Lower Recognition
            {
                "story_id": "ananias_sapphira",
                "name": "Ananias and Sapphira",
                "testament": "New",
                "book": "Acts",
                "chapters": "5",
                "verses": 11,
                "summary": "A couple lies to Peter about the price of land they sold. Both are struck dead by God for their deception.",
                "characters": ["Ananias", "Sapphira", "Peter", "God"],
                "has_underdog": False,
                "has_villain": True,
                "has_miracle": True,
                "has_violence": True,
                "moral_clarity": "medium",
                "visual_iconic": False,
                "metaphor_potential": "low",
                "children_bible_inclusion": 0.0,
                "estimated_cultural_persistence": 0.18
            },
            {
                "story_id": "dorcas_raised",
                "name": "Raising of Dorcas",
                "testament": "New",
                "book": "Acts",
                "chapters": "9",
                "verses": 43,
                "summary": "Peter raises Dorcas (Tabitha), a woman known for good works, from the dead in Joppa.",
                "characters": ["Peter", "Dorcas", "Widows"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": False,
                "moral_clarity": "high",
                "visual_iconic": False,
                "metaphor_potential": "low",
                "children_bible_inclusion": 0.1,
                "estimated_cultural_persistence": 0.11
            },
            {
                "story_id": "eutychus_falls",
                "name": "Eutychus Falls from Window",
                "testament": "New",
                "book": "Acts",
                "chapters": "20",
                "verses": 12,
                "summary": "During Paul's lengthy sermon, a young man named Eutychus falls asleep and falls from a third-story window. Paul raises him from the dead.",
                "characters": ["Paul", "Eutychus"],
                "has_underdog": False,
                "has_villain": False,
                "has_miracle": True,
                "has_violence": True,
                "moral_clarity": "medium",
                "visual_iconic": False,
                "metaphor_potential": "low",
                "children_bible_inclusion": 0.0,
                "estimated_cultural_persistence": 0.09
            },
        ]
        
        self.stories = stories
        return stories
    
    def save_raw_data(self):
        """Save raw collected data"""
        output_file = self.output_dir / "bible_stories_raw.json"
        
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump({
                'collection_date': datetime.now().isoformat(),
                'total_stories': len(self.stories),
                'stories': self.stories
            }, f, indent=2, ensure_ascii=False)
        
        print(f"✓ Saved {len(self.stories)} Bible stories to {output_file}")
        return output_file

def main():
    """Collect Bible story data"""
    print("📖 Collecting Bible Stories Data...")
    print("=" * 70)
    
    collector = BibleStoryCollector()
    
    # Collect stories
    stories = collector.collect_stories()
    print(f"\n✓ Collected {len(stories)} Bible stories")
    
    # Show distribution
    old_testament = [s for s in stories if s['testament'] == 'Old']
    new_testament = [s for s in stories if s['testament'] == 'New']
    high_persistence = [s for s in stories if s['estimated_cultural_persistence'] >= 0.8]
    low_persistence = [s for s in stories if s['estimated_cultural_persistence'] < 0.3]
    
    print(f"\nDistribution:")
    print(f"  Old Testament: {len(old_testament)}")
    print(f"  New Testament: {len(new_testament)}")
    print(f"  High cultural persistence (≥0.8): {len(high_persistence)}")
    print(f"  Low cultural persistence (<0.3): {len(low_persistence)}")
    
    # Save data
    output_file = collector.save_raw_data()
    
    print(f"\n✓ Bible story data collection complete!")
    print(f"  Output: {output_file}")

if __name__ == "__main__":
    main()

